const fathulMuinLinks = [
  "https://www.youtube.com/watch?v=8vteh-jJx3o&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=1",
  "https://www.youtube.com/watch?v=uciZM1SrkPA&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=2",
  "https://www.youtube.com/watch?v=yTM66P8vvc0&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=3",
  "https://www.youtube.com/watch?v=wyMYysDzwYw&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=4",
  "https://www.youtube.com/watch?v=45T23BED4iM&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=5",
  "https://www.youtube.com/watch?v=BTyldBkOysQ&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=6",
  "https://www.youtube.com/watch?v=YmeXaFVGk3k&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=7",
  "https://www.youtube.com/watch?v=PwVXUHfnYwY&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=8",
  "https://www.youtube.com/watch?v=SF2vUOGsfkc&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=9",
  "https://www.youtube.com/watch?v=M1rFKIqOXQA&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=10",
  "https://www.youtube.com/watch?v=6f6qsVAJQTk&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=11",
  "https://www.youtube.com/watch?v=gme7OB7D2Ns&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=12",
  "https://www.youtube.com/watch?v=ydZ8gfHywIs&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=13",
  "https://www.youtube.com/watch?v=U28kOdomJCM&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=14",
  "https://www.youtube.com/watch?v=1HNg3zQjXL8&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=15",
  "https://www.youtube.com/watch?v=3uo-I9EyoWo&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=16",
  "https://www.youtube.com/watch?v=_afhUn2sFTE&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=17",
  "https://www.youtube.com/watch?v=FZWtXResk8w&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=18",
  "https://www.youtube.com/watch?v=pIMg-Mv3duk&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=19",
  "https://www.youtube.com/watch?v=Au4NtT5G-l4&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=20",
  "https://www.youtube.com/watch?v=gqCfxlkgWB4&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=21",
  "https://www.youtube.com/watch?v=K2nv3THOnZ8&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=22",
  "https://www.youtube.com/watch?v=Cb2jhnF1zGI&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=23",
  "https://www.youtube.com/watch?v=8nUJgTrsVeU&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=24",
  "https://www.youtube.com/watch?v=SQloJv2qp4Q&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=25",
  "https://www.youtube.com/watch?v=hbeSozwXcC4&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=26",
  "https://www.youtube.com/watch?v=ryQCu5oBPo4&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=27",
  "https://www.youtube.com/watch?v=pojXDmSooJQ&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=28",
  "https://www.youtube.com/watch?v=BxoVHYHBwM0&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=29",
  "https://www.youtube.com/watch?v=MioWaOPLa9A&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=30",
  "https://www.youtube.com/watch?v=uRlMWCG31_Y&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=31",
  "https://www.youtube.com/watch?v=nMzBJWYG4hI&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=32",
  "https://www.youtube.com/watch?v=Cm_DLbU5qTM&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=33",
  "https://www.youtube.com/watch?v=kAkWhyKIp2E&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=34",
  "https://www.youtube.com/watch?v=xCo0bvb7HxU&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=35",
  "https://www.youtube.com/watch?v=SyLJ38zHo0Q&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=36",
  "https://www.youtube.com/watch?v=e630ey091SI&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=37",
  "https://www.youtube.com/watch?v=vJPtYA50sBE&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=38",
  "https://www.youtube.com/watch?v=L--AVhWl4BI&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=39",
  "https://www.youtube.com/watch?v=GmslTAwGZp4&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=40",
  "https://www.youtube.com/watch?v=UF5sQzO1HW8&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=41",
  "https://www.youtube.com/watch?v=1ilPPisJrAo&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=42",
  "https://www.youtube.com/watch?v=53p-jVV60_o&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=43",
  "https://www.youtube.com/watch?v=vXvwyCgPDDY&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=44",
  "https://www.youtube.com/watch?v=wq-AVUUlWgc&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=45",
  "https://www.youtube.com/watch?v=LUs0rev3SwA&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=46",
  "https://www.youtube.com/watch?v=tSd9Bcgxc7E&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=47",
  "https://www.youtube.com/watch?v=i_d49EUw3ww&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=48",
  "https://www.youtube.com/watch?v=ristR2abr6c&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=49",
  "https://www.youtube.com/watch?v=RqERdFuMapI&list=PL7cjLZ8WuCQI_gfGGa_vngENXXSHuy4KC&index=50",
]

const alIbanaLinks = [
  "https://www.youtube.com/watch?v=5YHsfHTJg-4&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=1",
  "https://www.youtube.com/watch?v=bgHJeZIxrMQ&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=2",
  "https://www.youtube.com/watch?v=O0qY0c58FAU&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=3",
  "https://www.youtube.com/watch?v=YNU0nzBWEXU&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=4",
  "https://www.youtube.com/watch?v=GrrcnWxkKTY&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=5",
  "https://www.youtube.com/watch?v=-XQgoolRNdk&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=6",
  "https://www.youtube.com/watch?v=L_nQ6AovI5M&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=7",
  "https://www.youtube.com/watch?v=AUpqP8acBxI&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=8",
  "https://www.youtube.com/watch?v=8oJrLTibr0o&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=9",
  "https://www.youtube.com/watch?v=rklzn8y71d0&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=10",
  "https://www.youtube.com/watch?v=p_JeZgiSs2w&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=11",
  "https://www.youtube.com/watch?v=OoFqON7HBc8&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=12",
  "https://www.youtube.com/watch?v=cA5DzB_-7zo&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=13",
  "https://www.youtube.com/watch?v=bYdlI9KTnAk&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=14",
  "https://www.youtube.com/watch?v=b_zI-uSyUa0&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=15",
  "https://www.youtube.com/watch?v=4y6ds0jH904&list=PL7cjLZ8WuCQITy5Neb9i5aUIhAuTG_WJb&index=16",
]

export const youtubeLinks: Record<string, string[]> = {
  'fath-al-muin': fathulMuinLinks,
  'al-ibana': alIbanaLinks,
}
